# The Docker image that will be used to build your app
image: node:lts
# Functions that should be executed before the build script is run
before_script:
  - npm install sass
stage: deploy
pages:
  stage: deploy
  script:
  - mv sass/ public
  - mv index.html/ public
  - mv scripts/ public
  - mv imgs/ public
  artifacts:
    paths:
    - public